- name : variable as promt
  hosts : localhost
  vars_prompt:
   - name : username
     prompt : "what is your name"
     private : yes
  tasks:
   - name : student name
     ansible.builtin.debug:
       msg: "my name is: {{username}}"
     