- name: variable via inventory file
  hosts: local
  connection: local
  tasks:
    - name: student info
      ansible.builtin.debug:
        msg: "my name is: {{ name }},age is: {{ age }},and course is: {{ course }}"