- name : Gathering facts
  hosts : localhost
  tasks:
   - name : facts
     ansible.builtin.debug:
      msg: "{{ansible_facts}}"  #server colectects all the information of server and store in ansible_facts 