- name : installing packages using loops
  hosts  : localhost
  becomee : yes
  tasks:
   - name : installing packages
     ansible.builtin.package:
      name : "{{item}}"
      state : present
     loop :
      - nginx
      - mysql
    