- name : functions
  hosts : localhost
  vars:
   course :  Devops engineer,Aws
   topics : 
    - shell
    - ansible
    - linux
  tasks:
   - name : string to list
     ansible.builtin.debug:
      msg : "{{course | split(',')}}" #split is a function which is used to split the string and it will return list and we are using index 0 to get the first word of the string

   - name : list to dictonary or map
     ansible.builtin.debug:
      msg : "{{topics | items2dict}}" #items2dict is a function which is used to convert list to dictonary or map and it will return dictonary or map and we are using index 0 to get the first word of the string